# Generated by Django 3.1.6 on 2021-07-29 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tbs_dept_code', models.CharField(max_length=10)),
                ('legal_name_en', models.TextField()),
                ('legal_name_fr', models.TextField()),
                ('applied_title_en', models.TextField()),
                ('applied_title_fr', models.TextField()),
                ('abbr_en', models.TextField()),
                ('abbr_fr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='ReportVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='firstapp.department', verbose_name='department')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eternal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='firstapp.report')),
            ],
            options={
                'ordering': ['business_date'],
                'get_latest_by': 'business_date',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field', models.TextField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='firstapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dept_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentGroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field', models.TextField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to='firstapp.department')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dept_profile', to='auth.group')),
            ],
        ),
    ]
